# Generated by Django 2.0.3 on 2018-03-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='updated',
        ),
    ]
