# Generated by Django 2.0.3 on 2018-03-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_url_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
