# Generated by Django 2.0.3 on 2018-04-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20180414_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='active',
        ),
    ]
