# Generated by Django 2.0.3 on 2018-04-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_remove_url_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
